services:
  app:
    build:
      context: .
      target: testbase
      dockerfile: Dockerfile
    command: "tail -F /dev/null"
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules

volumes:
  node_modules:
